# 2025-08-04, 김병현 수정 - 로컬 의존성을 고려한 빌드 순서
FROM node:22-alpine AS builder
# Set the working directory
WORKDIR /app

# Copy the server's package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 5173

CMD ["npm", "run", "dev"]
